### PR TITLE
Don't fail when encountering invalid files, skip them

### PR DESCRIPTION
**Pull request by traxys**
When I tried to use `lk` on a large tree of directories it encountered some files it could not read. Instead of failing, I just made the option to skip them

### CODE REVIEW

**Comment by jamescoleuk** [comment]
Awesome! Thank you @traxys! I had plans for something like this that involved the config in `~/.config/lk/lk.toml`, but that wouldn't be project-specific. I'm not quite ready for project-specific config yet: I don't really think this tool warrents another dot file in a project root! So something like this seems ideal. I'll have to review in more detail this weekend, but I promise I'll get it done by Sunday night.

I was thinking of a "don't walk sub-dirs" option. This would mean all scripts would have to live in the project root but for me they tend to anyway. This could be a global `lk` setting. How would this work for you?

**Comment by traxys** [comment]
I had launched `lk` in a directory where I have a lot of related projects, that have a lot of scripts that have common parts, so not walking into subdirs would defeat this purpose. Though I don't know if I would end up using `lk` like that.

I have another patch in order to skip subdirectories in when seaching for executables if your are interested

**Comment by jamescoleuk** [comment]
I encountered a bunch of problems when walking the dirs and making that more robust is important. So [f5246d5](https://github.com/jamescoleuk/lk/pull/6/commits/f5246d5352c4ec98b59edf45a11f9458162f8e61) is a solid fix, thank you.

I like [74a1534](https://github.com/jamescoleuk/lk/pull/6/commits/74a15342063c01e9a0cc51c36677f52f39765950) for the number of results. It's definitely a feature `lk` should have. But might it be more useful as a global setting? As in it operates more like `--default`. Would you be interested in doing that? 

I see that skipping subdirs is essential for your use case and I want to support that. `--skips` does that. I imagine in this scenario you'd get tired typing `--skips foobar` all the time. Would you find it easier to add a `.lkignore` file? Maybe that's something I could add later of course, but I'm hesitant to add `--skips` to the args only to change or remove it later: the args are a contract. Removing something is a breaking change. But I suppose there's no harm in supporting both, with the args taking precedence (although in this case the arg name should I think be `--ignore`). What are your thoughts?

**Comment by traxys** [comment]
I think it's nice to have both args & config, args for quickly figuring out what you want, and when you are sure you can add it to your config file. And yeah, args should override the config IMO

I am not very good to choose names, so another name like `ignore` or `exclude` could be better.

**Comment by jamescoleuk** [comment]
Great, I agree. I think I'd like to go with `ignore`. Are you happy to make that change? I think we're ready for merge after that.

**Comment by traxys** [comment]
I changed to ignore & rebase on main

**Comment by jamescoleuk** [comment]
Thanks for your work traxys. Your MRs are welcome any time.

**Pull request merged**
