### PR TITLE
Fixed creating a configuration directory

### PR DESCRIPTION
**Pull request by lmburns**
I changed the `Path` variable to a `PathBuf` and created it as its own variable instead of checking against a temporary variable. Then after the check of existence, I create the path if it doesn't exist. Without this, `$HOME/.config/lk` has to be created manually otherwise the program fails

### CODE REVIEW

**Comment by jamescoleuk** [comment]
First PR! Thanks Lucas. I'd love to hear if you're considering making `lk` part of your workflow, and if not is there anything that could change to make it fit better for you?

**Comment by lmburns** [comment]
@jamescoleuk Yes, I am going to start using it. I found this repository on [lib.rs](https://lib.rs/command-line-utilities) and thought that the idea of the application was very interesting. 

Here are some possible suggestions:
1. I think that it is pretty cool that you wrote the interface the the fuzzy finder and may possibly use that as an example for something I do in the future. However, adding a compilation flag to be able to use the `skim` crate as a library would be nice. I've added an option in a fork that I modified to use the environment variable `$SKIM_DEFAULT_OPTIONS` since the library (at least at the time) didn't support an option for parsing it directly. It can be found [here](https://github.com/lmburns/prs/blob/193b65f6f3df9812b5562624fca2128f5233fad7/cli/src/util/select_skim.rs#L15). There are also options of using the `fzf` or `skim` binary directly, and examples can also be found in the [same repository](https://github.com/lmburns/prs/blob/master/cli/src/util/select_fzf_bin.rs). Note that the code is a mixture of mine and the original repository's owner.
2. Adding a command line flag to either add in whole scripts or to only list whole scripts. This would allow the user to run the entire script file instead of just a function pulled from that file. This would also allow for these scripts to not be in the `$PATH` environment variable, the same as how the functions are pulled from scripts found from crawling the current directory.

If there are other things that I think of, I will let you know. I just thought that the idea of the application was interesting and that I hadn't seen it before. I will use this in projects where I am running a script that is made specifically for that project. There are tools that have been developed to do this already however. Mostly if the command is very short, i.e., [`just`](https://github.com/casey/just), [`pier`](https://github.com/pier-cli/pier), [`pet`](https://github.com/knqyf263/pet). 

I used to write a lot more shell code than what I do now, but I'd like to start using this more. If I get any time, I may submit more pull requests

**Comment by jamescoleuk** [comment]
Thanks for those thoughts Lucas, and sorry for taking so long to response. I looked at some of those other tools but they didn't quite fit. I just wanted to write bash and I wanted something to remind me what I could do in a given project.

Can I ask about your second point please? `lk` actually sources the script file, so anything outside a function will run. I guess I don't make this very clear in the docs. But that's useful for me because it allows me to set up environment variables and check for config in the main body of the script, and then have the functions depend upon them. Is this what you meant? Or were you perhaps thinking of a scenario where the functionality is the whole script file, rather than being embedded in a function in the script file?

**Comment by jamescoleuk** [comment]
I might add that the fuzzy find interface was a huge pain and I'm not yet happy with it! I do intent to improve it and maybe make it a standalone library so people can use it in their own CLI apps.

**Pull request merged**
